### PR TITLE
Update Checker Workflow Wrapper

### PR DESCRIPTION
**Pull request by garyluu**
- Input Parameters were somehow duplicated in previous PR, removing those
- Changed `validate__grading_summary` to a single file
- Pretty print the json because cwltool doesn't like tabs

Overall, passed cwltool validation now

### CODE REVIEW

**Comment by garyluu** [comment]
Still working on pretty print json

**Comment by denis-yuen** [comment]
Also note that the path for the checker workflow has changed from 
/wes-agha-test/bcbio-validation-checker/checker-workflow-wrapping-tool.cwl
to 
/wes-agha-test/checker-workflow-wrapping-tool.cwl

We ran into what looks like an odd regression issue with "../" references

**Comment by garyluu** [comment]
Fixed pretty printed json, hide white space changes to check that nothing vital changed

**Comment by chapmanb** [comment]
Gary -- thank so much for this. Apologies, I was working on swapping over to gs URLs to support Cromwell with the GCP workflow, causing conflicts with your pretty print/json changes. I autogenerate those files with `json.dump` from python and they shouldn't have tabs. Do you have an idea what was breaking? Is it possible to take out that change so I can merge the rest of your fixes? Sorry about breaking this.

**Comment by garyluu** [comment]
I've reverted the pretty print json.  I've previously gotten
```
gluu@ODL-GARYLUU:~/bcbio_validation_workflows/wes-agha-test$ cwltool checker-workflow-wrapping-tool.cwl wes_chr21_test-workflow-gcp/main-wes_chr21_test-samples.json 
/home/gluu/.local/bin/cwltool 1.0.20180403145700
Resolved 'checker-workflow-wrapping-tool.cwl' to 'file:///home/gluu/bcbio_validation_workflows/wes-agha-test/checker-workflow-wrapping-tool.cwl'
while scanning for the next token
found character '\t' that cannot start any token
  in "file:///home/gluu/bcbio_validation_workflows/wes-agha-test/wes_chr21_test-workflow-gcp/main-wes_chr21_test-samples.json", line 5, column 5
```
which is why I pretty printed it.

Your current file seems fine though.

**Comment by chapmanb** [comment]
Thanks again for this. I updated the checker workflow references in Dockstore so that should all be good to go as well. I appreciate all the help and testing.

**Pull request merged**
